import type { Metadata } from "next";
import "./globals.css";

import { Header } from "../compoments/header/index"
import { Footer } from "@/compoments/footer";

export const metadata: Metadata = {
  title: "Create Next App Primeiro",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Header buttons="Button"/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
